version: '3.7'
services:
  orla-project:
    image: orla-project
    build: .
    ports:
      - '8080:8080'
    environment:
      DB_NAME: orla
      DB_PASS: master
      DB_USER: postgres
      DB_URL: postgres
  postgres:
    image: postgres
    volumes:
      - './sql/DDL.sql:/docker-entrypoint-initdb.d/01-DDL.sql'
    environment:
      POSTGRES_PASSWORD: master
      POSTGRES_DB: orla
    ports:
      - '5432:5432'
